apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: builddemo 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: builddemo 
    spec:
      containers:
        - name: builddemo 
          image: shasb.azurecr.io/builddemo 
          ports:
          - containerPort: 8080