apiVersion: v1
kind: Service
metadata:
  name: bootcamp-demo
  labels:
    app: bootcamp-demo
spec:
  selector:
    app: bootcamp-demo
  ports:
  - name: metrics
    port: 8000
    protocol: TCP
    targetPort: 8000
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  type: ClusterIP
